name: shohozkaz
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  icons_plus: ^5.0.0
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.3
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1
  get: ^4.7.2
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  dropdown_search: ^6.0.2
  smooth_page_indicator: ^1.2.1
  fl_chart: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo/logo.png
    - assets/images/logo/google.png
    - assets/images/
    - assets/images/banner/
    - assets/animations/loading/

# For details regarding adding assets from package dependencies for slash screen,
flutter_native_splash:
  color: "#ffffff"  # Background color
  image: assets/images/logo/logo.png  # Path to your logo
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  android_12:
    image: assets/images/logo/logo.png
    icon_background_color: "#ffffff"


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
