// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLNGtTs-fw4ZMVWpM6r0cQwE90kcm1hY',
    appId: '1:349686080727:web:3b53b0a33e816d52217c92',
    messagingSenderId: '349686080727',
    projectId: 'shohozkaz',
    authDomain: 'shohozkaz.firebaseapp.com',
    storageBucket: 'shohozkaz.firebasestorage.app',
    measurementId: 'G-K40VS4B6GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiKSzcOyQ4LeqXz67jGpco5HVFU1e2YG8',
    appId: '1:349686080727:android:ceb5ccab271dc875217c92',
    messagingSenderId: '349686080727',
    projectId: 'shohozkaz',
    storageBucket: 'shohozkaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQKMaKHBo9aN12fGM-EriVCV9KzLmT4A',
    appId: '1:349686080727:ios:d9ea6ada6333f6b1217c92',
    messagingSenderId: '349686080727',
    projectId: 'shohozkaz',
    storageBucket: 'shohozkaz.firebasestorage.app',
    iosClientId: '349686080727-robs952iiknr6b6pae5mtrtdvjds12on.apps.googleusercontent.com',
    iosBundleId: 'com.example.shohozkaz',
  );
}
